# Online Retail Dataset - EDA

Exploring the Online Retail dataset to understand its structure and prepare for customer segmentation.

**Dataset**: Transactional data from a UK-based online retail company (2010-2011)

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Set visualization style
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

print("✓ Libraries imported successfully")

✓ Libraries imported successfully

## Load Dataset

In [27]:
# Load the Online Retail dataset
# Using utf-8-sig to handle BOM (Byte Order Mark) character
df = pd.read_csv(r"C:\Users\weezh\OneDrive\Desktop\pyhercules\dataset\online+retail\Online Retail.csv", encoding='utf-8-sig')

# Strip whitespace from column names
df.columns = df.columns.str.strip()

print(f"Dataset Shape: {df.shape}")
print(f"\nColumns: {df.columns.tolist()}")
print(f"\nData Types:\n{df.dtypes}")
print(f"\nDataset Preview:")
df.head(10)

Dataset Shape: (541909, 8)

Columns: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Data Types:
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

Dataset Preview:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,1/12/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,1/12/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,1/12/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,1/12/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,1/12/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,1/12/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,1/12/2010 8:34,1.69,13047.0,United Kingdom

## Missing Values Analysis

In [28]:
# Check for missing values
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Percentage': missing_pct
})
print("Missing Values Summary:")
print(missing_df[missing_df['Missing Count'] > 0])

print(f"\n\nTotal rows: {len(df)}")
print(f"Rows with missing CustomerID: {df['CustomerID'].isnull().sum()}")

Missing Values Summary:
             Missing Count  Percentage
Description           1454    0.268311
CustomerID          135080   24.926694


Total rows: 541909
Rows with missing CustomerID: 135080

## Basic Statistics

In [29]:
# Basic statistics
print("Numerical Columns Statistics:")
print(df.describe())

print("\n\nUnique Value Counts:")
print(f"Unique Invoices: {df['InvoiceNo'].nunique()}")
print(f"Unique Products (StockCode): {df['StockCode'].nunique()}")
print(f"Unique Customers: {df['CustomerID'].nunique()}")
print(f"Unique Countries: {df['Country'].nunique()}")

print("\n\nSample of Product Descriptions:")
print(df['Description'].value_counts().head(10))

Numerical Columns Statistics:
            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000


Unique Value Counts:
Unique Invoices: 25900
Unique Products (StockCode): 4070
Unique Customers: 4372
Unique Countries: 38


Sample of Product Descriptions:
Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
ASSORTED COLOUR BIRD ORNAMENT         1501
SET OF 3 CAKE TINS PANTRY DESIGN      1473
PACK OF 72 RETROSPOT CAKE CASES       1385
LUNCH BAG  BLACK SKULL.               1350
NATURAL SLATE HEART CHALKBOARD        1280
Name: count, dtype: int64

## Date Range Analysis

In [30]:
# Convert InvoiceDate to datetime (UK format: day/month/year)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], dayfirst=True)

print("Date Range:")
print(f"First transaction: {df['InvoiceDate'].min()}")
print(f"Last transaction: {df['InvoiceDate'].max()}")
print(f"Time span: {(df['InvoiceDate'].max() - df['InvoiceDate'].min()).days} days")

# Extract time features for analysis
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['DayOfWeek'] = df['InvoiceDate'].dt.dayofweek
df['Hour'] = df['InvoiceDate'].dt.hour

print("\n\nTransactions by Year-Month:")
print(df.groupby(['Year', 'Month']).size().head(15))

Date Range:
First transaction: 2010-12-01 08:26:00
Last transaction: 2011-12-09 12:50:00
Time span: 373 days


Transactions by Year-Month:
Year  Month
2010  12       42481
2011  1        35147
      2        27707
      3        36748
      4        29916
      5        37030
      6        36874
      7        39518
      8        35284
      9        50226
      10       60742
      11       84711
      12       25525
dtype: int64

## Sample Invoice Analysis

In [31]:
# Look at a sample invoice to understand the structure
sample_invoice = df['InvoiceNo'].iloc[100]
print(f"Sample Invoice: {sample_invoice}")
print(f"\nAll items in this invoice:")
sample_df = df[df['InvoiceNo'] == sample_invoice]
print(sample_df[['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'UnitPrice', 'CustomerID', 'Country']])

print("\n\nInvoice Summary:")
print(f"Total items in invoice: {len(sample_df)}")
print(f"Total revenue: £{(sample_df['Quantity'] * sample_df['UnitPrice']).sum():.2f}")

Sample Invoice: 536378

All items in this invoice:
    InvoiceNo StockCode                          Description  Quantity  \
86     536378     22386              JUMBO BAG PINK POLKADOT        10
87     536378    85099C       JUMBO  BAG BAROQUE BLACK WHITE        10
88     536378     21033      JUMBO BAG CHARLIE AND LOLA TOYS        10
89     536378     20723             STRAWBERRY CHARLOTTE BAG        10
90     536378    84997B    RED 3 PIECE RETROSPOT CUTLERY SET        12
91     536378    84997C    BLUE 3 PIECE POLKADOT CUTLERY SET         6
92     536378     21094        SET/6 RED SPOTTY PAPER PLATES        12
93     536378     20725              LUNCH BAG RED RETROSPOT        10
94     536378     21559    STRAWBERRY LUNCH BOX WITH CUTLERY         6
95     536378     22352    LUNCH BOX WITH CUTLERY RETROSPOT          6
96     536378     21212      PACK OF 72 RETROSPOT CAKE CASES       120
97     536378     21975       PACK OF 60 DINOSAUR CAKE CASES        24
98     536378     21977   PACK OF 60 PINK PAISLEY CAKE CASES        24
99     536378     84991          60 TEATIME FAIRY CAKE CASES        24
100    536378    84519A      TOMATO CHARLIE+LOLA COASTER SET         6
101    536378    85183B  CHARLIE & LOLA WASTEPAPER BIN FLORA        48
102    536378    85071B   RED CHARLIE+LOLA PERSONAL DOORSIGN        96
103    536378     21931               JUMBO STORAGE BAG SUKI        10
104    536378     21929       JUMBO BAG PINK VINTAGE PAISLEY        10

     UnitPrice  CustomerID         Country
86        1.95     14688.0  United Kingdom
87        1.95     14688.0  United Kingdom
88        2.95     14688.0  United Kingdom
89        0.85     14688.0  United Kingdom
90        3.75     14688.0  United Kingdom
91        3.75     14688.0  United Kingdom
92        0.85     14688.0  United Kingdom
93        1.65     14688.0  United Kingdom
94        2.55     14688.0  United Kingdom
95        2.55     14688.0  United Kingdom
96        0.42     14688.0  United Kingdom
97        0.55     14688.0  United Kingdom
98        0.55     14688.0  United Kingdom
99        0.55     14688.0  United Kingdom
100       2.95     14688.0  United Kingdom
101       1.25     14688.0  United Kingdom
102       0.38     14688.0  United Kingdom
103       1.95     14688.0  United Kingdom
104       1.95     14688.0  United Kingdom


Invoice Summary:
Total items in invoice: 19
Total revenue: £444.98

## Dataset Structure & Segmentation Strategy

**Dataset Structure:**
- **Transactional data**: Each row represents one product in an order/invoice
- Multiple rows can have the same InvoiceNo (multi-item orders)
- Each invoice belongs to one CustomerID
- Data spans multiple countries and time periods

**Key for Customer Segmentation:**
- **CustomerID**: Primary key for aggregating customer-level features
- **Note**: Some transactions have missing CustomerID (guest purchases) - we'll need to filter these

**Potential Features for Customer Segmentation:**

1. **RFM Metrics** (Classic segmentation approach):
   - **Recency**: Days since last purchase
   - **Frequency**: Number of orders/invoices
   - **Monetary**: Total revenue generated

2. **Behavioral Features**:
   - Average order value
   - Average basket size (items per order)
   - Purchase frequency (orders per month)
   - Product diversity (unique products purchased)
   - Preferred shopping time (hour/day patterns)

3. **Product Preferences**:
   - Most purchased product categories
   - Price sensitivity (avg unit price)
   - Return rate (negative quantities indicate returns)

4. **Geographic & Temporal**:
   - Country
   - Time span as customer
   - Consistency of purchases (std dev of order intervals)

## Data Quality Checks

In [32]:
# Check for returns and anomalies
print("Quantity Analysis:")
print(f"Total transactions: {len(df)}")
print(f"Transactions with negative quantity (returns): {(df['Quantity'] < 0).sum()}")
print(f"Transactions with zero quantity: {(df['Quantity'] == 0).sum()}")
print(f"Transactions with negative price: {(df['UnitPrice'] < 0).sum()}")
print(f"Transactions with zero price: {(df['UnitPrice'] == 0).sum()}")

print("\n\nCancelled Orders (InvoiceNo starting with 'C'):")
cancelled = df[df['InvoiceNo'].astype(str).str.startswith('C')]
print(f"Number of cancelled transactions: {len(cancelled)}")

print("\n\nCountry Distribution (Top 10):")
print(df['Country'].value_counts().head(10))

Quantity Analysis:
Total transactions: 541909
Transactions with negative quantity (returns): 10624
Transactions with zero quantity: 0
Transactions with negative price: 2
Transactions with zero price: 2515


Cancelled Orders (InvoiceNo starting with 'C'):
Number of cancelled transactions: 9288


Country Distribution (Top 10):
Country
United Kingdom    495478
Germany             9495
France              8557
EIRE                8196
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         2002
Portugal            1519
Australia           1259
Name: count, dtype: int64

## Customer-Level Summary

In [33]:
# Filter to only customers with valid CustomerID
df_customers = df[df['CustomerID'].notna()].copy()

print(f"Total transactions with valid CustomerID: {len(df_customers)}")
print(f"Unique customers: {df_customers['CustomerID'].nunique()}")

# Create a quick customer summary
customer_summary = df_customers.groupby('CustomerID').agg({
    'InvoiceNo': 'nunique',  # Number of orders
    'Quantity': 'sum',        # Total items purchased
    'InvoiceDate': ['min', 'max']  # First and last purchase
}).reset_index()

customer_summary.columns = ['CustomerID', 'NumOrders', 'TotalItems', 'FirstPurchase', 'LastPurchase']

# Calculate revenue per customer
df_customers['Revenue'] = df_customers['Quantity'] * df_customers['UnitPrice']
customer_revenue = df_customers.groupby('CustomerID')['Revenue'].sum().reset_index()
customer_summary = customer_summary.merge(customer_revenue, on='CustomerID')

print("\n\nCustomer Summary Statistics:")
print(customer_summary[['NumOrders', 'TotalItems', 'Revenue']].describe())

print("\n\nSample customers:")
customer_summary.head(10)

Total transactions with valid CustomerID: 406829
Unique customers: 4372


Customer Summary Statistics:
         NumOrders     TotalItems        Revenue
count  4372.000000    4372.000000    4372.000000
mean      5.075480    1122.344007    1898.459701
std       9.338754    4672.790720    8219.345141
min       1.000000    -303.000000   -4287.630000
25%       1.000000     153.000000     293.362500
50%       3.000000     365.000000     648.075000
75%       5.000000     962.250000    1611.725000
max     248.000000  196719.000000  279489.020000


Sample customers:

,CustomerID,NumOrders,TotalItems,FirstPurchase,LastPurchase,Revenue
0,12346.0,2,0,2011-01-18 10:01:00,2011-01-18 10:17:00,0.00
1,12347.0,7,2458,2010-12-07 14:57:00,2011-12-07 15:52:00,4310.00
2,12348.0,4,2341,2010-12-16 19:09:00,2011-09-25 13:13:00,1797.24
3,12349.0,1,631,2011-11-21 09:51:00,2011-11-21 09:51:00,1757.55
4,12350.0,1,197,2011-02-02 16:01:00,2011-02-02 16:01:00,334.40
5,12352.0,11,470,2011-02-16 12:33:00,2011-11-03 14:37:00,1545.41
6,12353.0,1,20,2011-05-19 17:47:00,2011-05-19 17:47:00,89.00
7,12354.0,1,530,2011-04-21 13:11:00,2011-04-21 13:11:00,1079.40
8,12355.0,1,240,2011-05-09 13:49:00,2011-05-09 13:49:00,459.40
9,12356.0,3,1591,2011-01-18 09:50:00,2011-11-17 08:40:00,2811.43

## Next Steps: Feature Engineering for Clustering

Based on this EDA, we can create a customer-level feature matrix similar to the Instacart approach:

**Proposed Features:**

1. **RFM Features (3)**:
   - Recency (days since last purchase from the reference date)
   - Frequency (total number of orders)
   - Monetary (total revenue)

2. **Purchase Behavior (5)**:
   - Total items purchased
   - Average basket size (items per order)
   - Average order value (revenue per order)
   - Total unique products purchased
   - Purchase span (days between first and last purchase)

3. **Patterns (4)**:
   - Average days between orders
   - Most frequent purchase day of week
   - Most frequent purchase hour
   - Purchase consistency (std dev of order intervals)

4. **Product Preferences (3)**:
   - Average unit price (price sensitivity)
   - Return rate (% of returned items)
   - Unique products to total items ratio (exploration tendency)

5. **Geographic (1)**:
   - Country (will need encoding)

**Data Cleaning Needed:**
- Filter out transactions with missing CustomerID
- Handle cancelled orders (InvoiceNo starting with 'C')
- Consider whether to include returns/negative quantities in features

---

# Feature Engineering for Customer Segmentation

## Data Cleaning & Filtering

In [34]:
# Create a clean dataframe for feature engineering
# Remove rows with missing CustomerID
df_clean = df[df['CustomerID'].notna()].copy()

# Remove cancelled orders (InvoiceNo starting with 'C')
df_clean = df_clean[~df_clean['InvoiceNo'].astype(str).str.startswith('C')]

# Calculate revenue
df_clean['Revenue'] = df_clean['Quantity'] * df_clean['UnitPrice']

# Get reference date (one day after last transaction for recency calculation)
reference_date = df_clean['InvoiceDate'].max() + pd.Timedelta(days=1)

print("Data Cleaning Summary:")
print(f"Original transactions: {len(df)}")
print(f"After removing missing CustomerID: {len(df[df['CustomerID'].notna()])}")
print(f"After removing cancellations: {len(df_clean)}")
print(f"Unique customers for analysis: {df_clean['CustomerID'].nunique()}")
print(f"\nReference date for recency: {reference_date}")

Data Cleaning Summary:
Original transactions: 541909
After removing missing CustomerID: 406829
After removing cancellations: 397924
Unique customers for analysis: 4339

Reference date for recency: 2011-12-10 12:50:00

## RFM Features (Recency, Frequency, Monetary)

In [35]:
# Calculate RFM features
rfm = df_clean.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (reference_date - x.max()).days,  # Recency
    'InvoiceNo': 'nunique',  # Frequency
    'Revenue': 'sum'  # Monetary
}).reset_index()

rfm.columns = ['CustomerID', 'Recency', 'Frequency', 'Monetary']

print("RFM Features:")
print(rfm.head(10))
print(f"\nRFM Statistics:")
print(rfm[['Recency', 'Frequency', 'Monetary']].describe())

RFM Features:
   CustomerID  Recency  Frequency  Monetary
0     12346.0      326          1  77183.60
1     12347.0        2          7   4310.00
2     12348.0       75          4   1797.24
3     12349.0       19          1   1757.55
4     12350.0      310          1    334.40
5     12352.0       36          8   2506.04
6     12353.0      204          1     89.00
7     12354.0      232          1   1079.40
8     12355.0      214          1    459.40
9     12356.0       23          3   2811.43

RFM Statistics:
           Recency    Frequency       Monetary
count  4339.000000  4339.000000    4339.000000
mean     92.518322     4.271952    2053.793018
std     100.009747     7.705493    8988.248381
min       1.000000     1.000000       0.000000
25%      18.000000     1.000000     307.245000
50%      51.000000     2.000000     674.450000
75%     142.000000     5.000000    1661.640000
max     374.000000   210.000000  280206.020000

## Purchase Behavior Features

In [36]:
# Calculate Purchase Behavior features
behavior = df_clean.groupby('CustomerID').agg({
    'Quantity': 'sum',  # Total items purchased
    'StockCode': 'nunique',  # Unique products
    'InvoiceDate': ['min', 'max']  # Date range
}).reset_index()

behavior.columns = ['CustomerID', 'TotalItems', 'UniqueProducts', 'FirstPurchase', 'LastPurchase']

# Calculate purchase span (days as customer)
behavior['PurchaseSpan'] = (behavior['LastPurchase'] - behavior['FirstPurchase']).dt.days

# Calculate average basket size and average order value per customer
basket_stats = df_clean.groupby(['CustomerID', 'InvoiceNo']).agg({
    'Quantity': 'sum',
    'Revenue': 'sum'
}).reset_index()

basket_avg = basket_stats.groupby('CustomerID').agg({
    'Quantity': 'mean',
    'Revenue': 'mean'
}).reset_index()

basket_avg.columns = ['CustomerID', 'AvgBasketSize', 'AvgOrderValue']

# Merge with behavior
behavior = behavior.merge(basket_avg, on='CustomerID')

# Drop date columns (already captured in Recency and PurchaseSpan)
behavior = behavior.drop(['FirstPurchase', 'LastPurchase'], axis=1)

print("Purchase Behavior Features:")
print(behavior.head(10))
print(f"\nBehavior Statistics:")
print(behavior.drop('CustomerID', axis=1).describe())

Purchase Behavior Features:
   CustomerID  TotalItems  UniqueProducts  PurchaseSpan  AvgBasketSize  \
0     12346.0       74215               1             0   74215.000000
1     12347.0        2458             103           365     351.142857
2     12348.0        2341              22           282     585.250000
3     12349.0         631              73             0     631.000000
4     12350.0         197              17             0     197.000000
5     12352.0         536              59           260      67.000000
6     12353.0          20               4             0      20.000000
7     12354.0         530              58             0     530.000000
8     12355.0         240              13             0     240.000000
9     12356.0        1591              53           302     530.333333

   AvgOrderValue
0   77183.600000
1     615.714286
2     449.310000
3    1757.550000
4     334.400000
5     313.255000
6      89.000000
7    1079.400000
8     459.400000
9     937.143333

Behavior Statistics:
          TotalItems  UniqueProducts  PurchaseSpan  AvgBasketSize  \
count    4339.000000     4339.000000   4339.000000    4339.000000
mean     1194.214335       61.489283    130.418530     256.313903
std      5055.603049       85.363900    132.039186    1325.939105
min         1.000000        1.000000      0.000000       1.000000
25%       160.000000       16.000000      0.000000      93.000000
50%       379.000000       35.000000     92.000000     161.750000
75%       993.000000       77.000000    251.500000     272.000000
max    197491.000000     1787.000000    373.000000   74215.000000

       AvgOrderValue
count    4339.000000
mean      419.047702
std      1796.320814
min         0.000000
25%       178.505000
50%       293.690000
75%       430.022500
max     84236.250000

## Pattern Features (Temporal & Shopping Patterns)

In [37]:
# Calculate Pattern features
# Get order dates per customer
order_dates = df_clean.groupby(['CustomerID', 'InvoiceNo'])['InvoiceDate'].min().reset_index()
order_dates = order_dates.sort_values(['CustomerID', 'InvoiceDate'])

# Calculate days between orders
def calculate_order_intervals(group):
    if len(group) > 1:
        intervals = group['InvoiceDate'].diff().dt.days.dropna()
        return pd.Series({
            'AvgDaysBetweenOrders': intervals.mean() if len(intervals) > 0 else 0,
            'StdDaysBetweenOrders': intervals.std() if len(intervals) > 0 else 0
        })
    else:
        return pd.Series({
            'AvgDaysBetweenOrders': 0,
            'StdDaysBetweenOrders': 0
        })

intervals_df = order_dates.groupby('CustomerID').apply(calculate_order_intervals).reset_index()

# Get preferred day of week and hour
time_prefs = df_clean.groupby('CustomerID').agg({
    'DayOfWeek': lambda x: x.mode()[0] if len(x.mode()) > 0 else x.iloc[0],
    'Hour': lambda x: x.mode()[0] if len(x.mode()) > 0 else x.iloc[0]
}).reset_index()

time_prefs.columns = ['CustomerID', 'PreferredDayOfWeek', 'PreferredHour']

# Merge pattern features
patterns = intervals_df.merge(time_prefs, on='CustomerID')

print("Pattern Features:")
print(patterns.head(10))
print(f"\nPattern Statistics:")
print(patterns.drop('CustomerID', axis=1).describe())

Pattern Features:
   CustomerID  AvgDaysBetweenOrders  StdDaysBetweenOrders  PreferredDayOfWeek  \
0     12346.0              0.000000              0.000000                   1
1     12347.0             60.333333             18.478817                   1
2     12348.0             94.000000             70.149840                   3
3     12349.0              0.000000              0.000000                   0
4     12350.0              0.000000              0.000000                   2
5     12352.0             36.857143             64.537918                   1
6     12353.0              0.000000              0.000000                   3
7     12354.0              0.000000              0.000000                   3
8     12355.0              0.000000              0.000000                   0
9     12356.0            151.000000            100.409163                   1

   PreferredHour
0             10
1             14
2             19
3              9
4             16
5             14
6             17
7             13
8             13
9              9

Pattern Statistics:
       AvgDaysBetweenOrders  StdDaysBetweenOrders  PreferredDayOfWeek  \
count           4339.000000           3504.000000         4339.000000
mean              47.326113             23.760211            2.543904
std               63.178844             33.887700            1.845607
min                0.000000              0.000000            0.000000
25%                0.000000              0.000000            1.000000
50%               28.000000             11.321664            2.000000
75%               68.000000             35.832422            4.000000
max              365.000000            242.537626            6.000000

       PreferredHour
count    4339.000000
mean       12.492049
std         2.317396
min         7.000000
25%        11.000000
50%        12.000000
75%        14.000000
max        20.000000

## Product Preference Features

In [38]:
# Calculate Product Preference features
product_prefs = df_clean.groupby('CustomerID').agg({
    'UnitPrice': 'mean',  # Average unit price (price sensitivity)
    'Quantity': ['sum', lambda x: (x < 0).sum()]  # Total quantity and returns count
}).reset_index()

product_prefs.columns = ['CustomerID', 'AvgUnitPrice', 'TotalQuantity', 'ReturnCount']

# Calculate return rate (% of transactions that are returns)
transaction_counts = df_clean.groupby('CustomerID').size().reset_index(name='TotalTransactions')
product_prefs = product_prefs.merge(transaction_counts, on='CustomerID')
product_prefs['ReturnRate'] = product_prefs['ReturnCount'] / product_prefs['TotalTransactions']

# Calculate exploration tendency (unique products / total items)
# Already have TotalItems and UniqueProducts in behavior df, will merge later
product_prefs = product_prefs.drop(['TotalQuantity', 'ReturnCount', 'TotalTransactions'], axis=1)

print("Product Preference Features:")
print(product_prefs.head(10))
print(f"\nProduct Preference Statistics:")
print(product_prefs.drop('CustomerID', axis=1).describe())

Product Preference Features:
   CustomerID  AvgUnitPrice  ReturnRate
0     12346.0      1.040000         0.0
1     12347.0      2.644011         0.0
2     12348.0      5.764839         0.0
3     12349.0      8.289041         0.0
4     12350.0      3.841176         0.0
5     12352.0     15.930706         0.0
6     12353.0      6.075000         0.0
7     12354.0      4.503793         0.0
8     12355.0      4.203846         0.0
9     12356.0      3.201186         0.0

Product Preference Statistics:
       AvgUnitPrice  ReturnRate
count   4339.000000      4339.0
mean       4.465257         0.0
std       34.207313         0.0
min        0.000000         0.0
25%        2.203233         0.0
50%        2.917444         0.0
75%        3.829567         0.0
max     2033.100000         0.0

## Geographic Features

In [39]:
# Get primary country per customer (most frequent)
geographic = df_clean.groupby('CustomerID')['Country'].agg(lambda x: x.mode()[0] if len(x.mode()) > 0 else x.iloc[0]).reset_index()
geographic.columns = ['CustomerID', 'Country']

print("Geographic Features:")
print(geographic.head(10))
print(f"\nCountry Distribution:")
print(geographic['Country'].value_counts().head(10))

Geographic Features:
   CustomerID         Country
0     12346.0  United Kingdom
1     12347.0         Iceland
2     12348.0         Finland
3     12349.0           Italy
4     12350.0          Norway
5     12352.0          Norway
6     12353.0         Bahrain
7     12354.0           Spain
8     12355.0         Bahrain
9     12356.0        Portugal

Country Distribution:
Country
United Kingdom    3921
Germany             94
France              87
Spain               29
Belgium             24
Switzerland         20
Portugal            19
Italy               14
Finland             12
Norway              10
Name: count, dtype: int64

## Merge All Features

In [40]:
# Merge all feature sets
features = rfm.copy()
features = features.merge(behavior, on='CustomerID', how='left')
features = features.merge(patterns, on='CustomerID', how='left')
features = features.merge(product_prefs, on='CustomerID', how='left')
features = features.merge(geographic, on='CustomerID', how='left')

# Calculate exploration tendency (unique products / total items)
features['ExplorationTendency'] = features['UniqueProducts'] / features['TotalItems']

# Fill NaN values in interval features (for customers with only 1 order)
features['AvgDaysBetweenOrders'].fillna(0, inplace=True)
features['StdDaysBetweenOrders'].fillna(0, inplace=True)

print("Merged Feature Matrix:")
print(features.head(10))
print(f"\nFeature Matrix Shape: {features.shape}")
print(f"\nColumns: {features.columns.tolist()}")
print(f"\nMissing values:")
print(features.isnull().sum())

Merged Feature Matrix:
   CustomerID  Recency  Frequency  Monetary  TotalItems  UniqueProducts  \
0     12346.0      326          1  77183.60       74215               1
1     12347.0        2          7   4310.00        2458             103
2     12348.0       75          4   1797.24        2341              22
3     12349.0       19          1   1757.55         631              73
4     12350.0      310          1    334.40         197              17
5     12352.0       36          8   2506.04         536              59
6     12353.0      204          1     89.00          20               4
7     12354.0      232          1   1079.40         530              58
8     12355.0      214          1    459.40         240              13
9     12356.0       23          3   2811.43        1591              53

   PurchaseSpan  AvgBasketSize  AvgOrderValue  AvgDaysBetweenOrders  \
0             0   74215.000000   77183.600000              0.000000
1           365     351.142857     615.714286             60.333333
2           282     585.250000     449.310000             94.000000
3             0     631.000000    1757.550000              0.000000
4             0     197.000000     334.400000              0.000000
5           260      67.000000     313.255000             36.857143
6             0      20.000000      89.000000              0.000000
7             0     530.000000    1079.400000              0.000000
8             0     240.000000     459.400000              0.000000
9           302     530.333333     937.143333            151.000000

   StdDaysBetweenOrders  PreferredDayOfWeek  PreferredHour  AvgUnitPrice  \
0              0.000000                   1             10      1.040000
1             18.478817                   1             14      2.644011
2             70.149840                   3             19      5.764839
3              0.000000                   0              9      8.289041
4              0.000000                   2             16      3.841176
5             64.537918                   1             14     15.930706
6              0.000000                   3             17      6.075000
7              0.000000                   3             13      4.503793
8              0.000000                   0             13      4.203846
9            100.409163                   1              9      3.201186

   ReturnRate         Country  ExplorationTendency
0         0.0  United Kingdom             0.000013
1         0.0         Iceland             0.041904
2         0.0         Finland             0.009398
3         0.0           Italy             0.115689
4         0.0          Norway             0.086294
5         0.0          Norway             0.110075
6         0.0         Bahrain             0.200000
7         0.0           Spain             0.109434
8         0.0         Bahrain             0.054167
9         0.0        Portugal             0.033312

Feature Matrix Shape: (4339, 17)

Columns: ['CustomerID', 'Recency', 'Frequency', 'Monetary', 'TotalItems', 'UniqueProducts', 'PurchaseSpan', 'AvgBasketSize', 'AvgOrderValue', 'AvgDaysBetweenOrders', 'StdDaysBetweenOrders', 'PreferredDayOfWeek', 'PreferredHour', 'AvgUnitPrice', 'ReturnRate', 'Country', 'ExplorationTendency']

Missing values:
CustomerID              0
Recency                 0
Frequency               0
Monetary                0
TotalItems              0
UniqueProducts          0
PurchaseSpan            0
AvgBasketSize           0
AvgOrderValue           0
AvgDaysBetweenOrders    0
StdDaysBetweenOrders    0
PreferredDayOfWeek      0
PreferredHour           0
AvgUnitPrice            0
ReturnRate              0
Country                 0
ExplorationTendency     0
dtype: int64

## Encode Country & Standardize Features

In [41]:
# One-hot encode Country (keep top 10 countries, group rest as 'Other')
top_countries = features['Country'].value_counts().head(10).index
features['Country_Grouped'] = features['Country'].apply(lambda x: x if x in top_countries else 'Other')

# One-hot encode
country_dummies = pd.get_dummies(features['Country_Grouped'], prefix='Country')
features = pd.concat([features, country_dummies], axis=1)

# Drop original Country columns
features = features.drop(['Country', 'Country_Grouped'], axis=1)

print("Features after encoding Country:")
print(f"Shape: {features.shape}")
print(f"Columns: {features.columns.tolist()}")

# Separate CustomerID from features
customer_ids = features['CustomerID'].copy()
feature_cols = [col for col in features.columns if col != 'CustomerID']

# Standardize features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features[feature_cols])

# Create final dataframe
features_final = pd.DataFrame(features_scaled, columns=feature_cols)
features_final.insert(0, 'CustomerID', customer_ids.values)

print("\n✓ Feature engineering complete!")
print(f"Final feature matrix shape: {features_final.shape}")
print(f"Features: {len(feature_cols)}")
print(f"\nFirst few rows:")
print(features_final.head())

Features after encoding Country:
Shape: (4339, 27)
Columns: ['CustomerID', 'Recency', 'Frequency', 'Monetary', 'TotalItems', 'UniqueProducts', 'PurchaseSpan', 'AvgBasketSize', 'AvgOrderValue', 'AvgDaysBetweenOrders', 'StdDaysBetweenOrders', 'PreferredDayOfWeek', 'PreferredHour', 'AvgUnitPrice', 'ReturnRate', 'ExplorationTendency', 'Country_Belgium', 'Country_Finland', 'Country_France', 'Country_Germany', 'Country_Italy', 'Country_Norway', 'Country_Other', 'Country_Portugal', 'Country_Spain', 'Country_Switzerland', 'Country_United Kingdom']

✓ Feature engineering complete!
Final feature matrix shape: (4339, 27)
Features: 26

First few rows:
   CustomerID   Recency  Frequency  Monetary  TotalItems  UniqueProducts  \
0     12346.0  2.334858  -0.424675  8.359634   14.445201       -0.708687
1     12347.0 -0.905199   0.354080  0.251046    0.250006        0.486336
2     12348.0 -0.175186  -0.035297 -0.028546    0.226861       -0.462653
3     12349.0 -0.735196  -0.424675 -0.032963   -0.111417        0.134858
4     12350.0  2.174855  -0.424675 -0.191315   -0.197272       -0.521232

   PurchaseSpan  AvgBasketSize  AvgOrderValue  AvgDaysBetweenOrders  ...  \
0     -0.987840      55.784772      42.739247             -0.749168  ...
1      1.776810       0.071527       0.109496              0.205903  ...
2      1.148136       0.248106       0.016849              0.738843  ...
3     -0.987840       0.282614       0.745221             -0.749168  ...
4     -0.987840      -0.044739      -0.047128             -0.749168  ...

   Country_Finland  Country_France  Country_Germany  Country_Italy  \
0        -0.052662       -0.143042        -0.148808      -0.056895
1        -0.052662       -0.143042        -0.148808      -0.056895
2        18.989032       -0.143042        -0.148808      -0.056895
3        -0.052662       -0.143042        -0.148808      17.576364
4        -0.052662       -0.143042        -0.148808      -0.056895

   Country_Norway  Country_Other  Country_Portugal  Country_Spain  \
0       -0.048062      -0.160525         -0.066319      -0.082028
1       -0.048062       6.229554         -0.066319      -0.082028
2       -0.048062      -0.160525         -0.066319      -0.082028
3       -0.048062      -0.160525         -0.066319      -0.082028
4       20.806249      -0.160525         -0.066319      -0.082028

   Country_Switzerland  Country_United Kingdom
0            -0.068049                0.326505
1            -0.068049               -3.062741
2            -0.068049               -3.062741
3            -0.068049               -3.062741
4            -0.068049               -3.062741

[5 rows x 27 columns]

## Save Feature Matrix

In [42]:
# Save to CSV for clustering
output_path = r"C:\Users\weezh\OneDrive\Desktop\pyhercules\dataset\9th exploration online retail\online_retail_user_features.csv"
features_final.to_csv(output_path, index=False)

print(f"✓ Feature matrix saved to: {output_path}")
print(f"\nSummary:")
print(f"- Total customers: {len(features_final)}")
print(f"- Total features: {len(feature_cols)}")
print(f"- Feature list: {feature_cols}")

✓ Feature matrix saved to: C:\Users\weezh\OneDrive\Desktop\pyhercules\dataset\9th exploration online retail\online_retail_user_features.csv

Summary:
- Total customers: 4339
- Total features: 26
- Feature list: ['Recency', 'Frequency', 'Monetary', 'TotalItems', 'UniqueProducts', 'PurchaseSpan', 'AvgBasketSize', 'AvgOrderValue', 'AvgDaysBetweenOrders', 'StdDaysBetweenOrders', 'PreferredDayOfWeek', 'PreferredHour', 'AvgUnitPrice', 'ReturnRate', 'ExplorationTendency', 'Country_Belgium', 'Country_Finland', 'Country_France', 'Country_Germany', 'Country_Italy', 'Country_Norway', 'Country_Other', 'Country_Portugal', 'Country_Spain', 'Country_Switzerland', 'Country_United Kingdom']