# Instacart PyHercules Clustering Analysis

This notebook replicates the PyHercules clustering process for the Instacart dataset:
1. Load and preprocess data (one-hot encoding, standard scaling)
2. Hierarchical K-means clustering (k=147 level 1, k=3 level 2)
3. Feature ranking by absolute z-score (top 10 most defining characteristics)
4. LLM-generated cluster descriptions using Google Gemini
5. Export cluster details and feature rankings to CSV

In [31]:
# Import required libraries
import pandas as pd
import numpy as np
import os
import json
import re
import warnings
from typing import Dict, List, Any, Tuple, Optional
from datetime import datetime

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

import google.generativeai as genai

warnings.filterwarnings('ignore')

print("All libraries imported successfully!")

All libraries imported successfully!

## 1. Load Data

In [32]:
# Load the Instacart dataset
data_path = r'C:\Users\weezh\OneDrive\Desktop\pyhercules\dataset\8th exploration instacart\instacart_user_features.csv'

df = pd.read_csv(data_path)
print(f"Dataset loaded: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"\nColumn names:\n{df.columns.tolist()}")
print(f"\nFirst few rows:")
df.head()

Dataset loaded: 206209 rows, 37 columns

Column names:
['user_id', 'total_orders', 'avg_days_between_orders', 'avg_basket_size', 'reorder_rate', 'total_products_purchased', 'unique_products', 'preferred_day_of_week', 'preferred_hour_of_day', 'day_consistency', 'hour_consistency', 'frequency_consistency', 'unique_aisles', 'unique_departments', 'product_exploration_rate', 'avg_products_per_aisle', 'dept_pct_alcohol', 'dept_pct_babies', 'dept_pct_bakery', 'dept_pct_beverages', 'dept_pct_breakfast', 'dept_pct_bulk', 'dept_pct_canned_goods', 'dept_pct_dairy_eggs', 'dept_pct_deli', 'dept_pct_dry_goods_pasta', 'dept_pct_frozen', 'dept_pct_household', 'dept_pct_international', 'dept_pct_meat_seafood', 'dept_pct_missing', 'dept_pct_other', 'dept_pct_pantry', 'dept_pct_personal_care', 'dept_pct_pets', 'dept_pct_produce', 'dept_pct_snacks']

First few rows:

,user_id,total_orders,avg_days_between_orders,avg_basket_size,reorder_rate,total_products_purchased,unique_products,preferred_day_of_week,preferred_hour_of_day,day_consistency,...,dept_pct_household,dept_pct_international,dept_pct_meat_seafood,dept_pct_missing,dept_pct_other,dept_pct_pantry,dept_pct_personal_care,dept_pct_pets,dept_pct_produce,dept_pct_snacks
0,1,10,19.555556,5.900000,0.694915,59,18,1,7,1.269296,...,0.033898,0.000000,0.000000,0.0,0.0,0.016949,0.000000,0.0,0.084746,0.372881
1,2,14,15.230769,13.928571,0.476923,195,102,1,10,1.231456,...,0.000000,0.015385,0.005128,0.0,0.0,0.056410,0.005128,0.0,0.184615,0.215385
2,3,12,12.090909,7.333333,0.625000,88,33,0,16,1.311372,...,0.011364,0.000000,0.000000,0.0,0.0,0.045455,0.000000,0.0,0.431818,0.102273
3,4,5,13.750000,3.600000,0.055556,18,17,4,11,0.836660,...,0.111111,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.111111,0.055556
4,5,4,13.333333,9.250000,0.378378,37,23,3,18,1.500000,...,0.000000,0.054054,0.000000,0.0,0.0,0.054054,0.000000,0.0,0.513514,0.027027

## 2. Data Preprocessing (Copy from PyHercules)

In [33]:
def detect_column_types(df: pd.DataFrame) -> Dict[str, str]:
    """
    Automatically detects column types as 'numeric', 'categorical', or 'text'.
    """
    types = {}
    
    for col in df.columns:
        # 1. Try to detect if column is actually numeric
        if pd.api.types.is_numeric_dtype(df[col]):
            types[col] = 'numeric'
            continue
        
        # Try converting to numeric
        try:
            numeric_converted = pd.to_numeric(df[col], errors='coerce')
            non_null_ratio = numeric_converted.notna().sum() / len(df[col])
            
            if non_null_ratio > 0.8:
                types[col] = 'numeric'
                continue
        except:
            pass
        
        # 2. For object/string columns, determine if categorical or text
        if df[col].dtype == 'object' or df[col].dtype.name == 'category':
            n_unique = df[col].nunique()
            n_total = len(df[col].dropna())
            
            if n_total == 0:
                types[col] = 'text'
                continue
                
            cardinality_ratio = n_unique / n_total
            avg_length = df[col].astype(str).str.len().mean()
            
            is_low_cardinality = cardinality_ratio < 0.05 or n_unique < 50
            is_short = avg_length < 30
            
            if is_low_cardinality and is_short:
                types[col] = 'categorical'
            else:
                types[col] = 'text'
        else:
            types[col] = 'text'
    
    return types


def preprocess_mixed_data(df: pd.DataFrame, 
                          column_types: Dict[str, str],
                          variable_metadata: Optional[Dict[str, Dict[str, Any]]] = None
                          ) -> Tuple[np.ndarray, List[str], Dict[str, Dict[str, Any]]]:
    """
    Preprocesses mixed data types (numeric, categorical, text) into a unified numerical representation.
    """
    processed_parts = []
    final_column_names = []
    metadata_out = variable_metadata.copy() if variable_metadata else {}
    
    for col, col_type in column_types.items():
        if col not in df.columns:
            continue
            
        if col_type == 'numeric':
            # Keep numeric columns as-is
            col_data = pd.to_numeric(df[col], errors='coerce')
            col_mean = col_data.mean()
            col_data = col_data.fillna(col_mean if not pd.isna(col_mean) else 0)
            processed_parts.append(col_data.values.reshape(-1, 1))
            final_column_names.append(col)
            if col not in metadata_out:
                metadata_out[col] = {'name': col, 'type': 'numeric', 'source_column': col}
                
        elif col_type == 'categorical':
            # One-hot encode categorical columns
            col_data = df[col].fillna('_MISSING_')
            encoded = pd.get_dummies(col_data, prefix=col, drop_first=False, dtype=float)
            if encoded.shape[1] > 0:
                processed_parts.append(encoded.values)
                for new_col in encoded.columns:
                    final_column_names.append(new_col)
                    category_value = new_col.replace(f"{col}_", "")
                    metadata_out[new_col] = {
                        'name': new_col,
                        'type': 'categorical_encoded',
                        'source_column': col,
                        'category': category_value
                    }
        
        elif col_type == 'text':
            # TF-IDF + SVD for text columns
            texts = df[col].fillna('').astype(str)
            
            if texts.str.strip().eq('').all():
                continue
            
            try:
                vectorizer = TfidfVectorizer(
                    max_features=100,
                    stop_words='english',
                    min_df=1,
                    max_df=0.95
                )
                tfidf_matrix = vectorizer.fit_transform(texts)
                
                n_components = min(10, tfidf_matrix.shape[1] - 1, tfidf_matrix.shape[0] - 1)
                if n_components > 0:
                    svd = TruncatedSVD(n_components=n_components, random_state=42)
                    text_features = svd.fit_transform(tfidf_matrix)
                    
                    processed_parts.append(text_features)
                    for i in range(text_features.shape[1]):
                        new_col_name = f"{col}_text_dim{i}"
                        final_column_names.append(new_col_name)
                        metadata_out[new_col_name] = {
                            'name': new_col_name,
                            'type': 'text_embedding',
                            'source_column': col,
                            'method': 'tfidf_svd',
                            'dimension': i
                        }
            except Exception as e:
                warnings.warn(f"Error processing text column '{col}': {e}. Skipping.")
                continue
    
    if not processed_parts:
        raise ValueError("No valid columns to process after preprocessing.")
    
    # Combine all processed parts
    combined_data = np.hstack(processed_parts)
    
    return combined_data, final_column_names, metadata_out


# Detect column types
column_types = detect_column_types(df)
print(f"\nDetected column types:")
for col, ctype in column_types.items():
    print(f"  {col}: {ctype}")

# Preprocess data
preprocessed_data, feature_names, metadata = preprocess_mixed_data(df, column_types)
print(f"\nPreprocessed data shape: {preprocessed_data.shape}")
print(f"Number of features after preprocessing: {len(feature_names)}")

Detected column types:
  user_id: numeric
  total_orders: numeric
  avg_days_between_orders: numeric
  avg_basket_size: numeric
  reorder_rate: numeric
  total_products_purchased: numeric
  unique_products: numeric
  preferred_day_of_week: numeric
  preferred_hour_of_day: numeric
  day_consistency: numeric
  hour_consistency: numeric
  frequency_consistency: numeric
  unique_aisles: numeric
  unique_departments: numeric
  product_exploration_rate: numeric
  avg_products_per_aisle: numeric
  dept_pct_alcohol: numeric
  dept_pct_babies: numeric
  dept_pct_bakery: numeric
  dept_pct_beverages: numeric
  dept_pct_breakfast: numeric
  dept_pct_bulk: numeric
  dept_pct_canned_goods: numeric
  dept_pct_dairy_eggs: numeric
  dept_pct_deli: numeric
  dept_pct_dry_goods_pasta: numeric
  dept_pct_frozen: numeric
  dept_pct_household: numeric
  dept_pct_international: numeric
  dept_pct_meat_seafood: numeric
  dept_pct_missing: numeric
  dept_pct_other: numeric
  dept_pct_pantry: numeric
  dept_pct_personal_care: numeric
  dept_pct_pets: numeric
  dept_pct_produce: numeric
  dept_pct_snacks: numeric

Preprocessed data shape: (206209, 37)
Number of features after preprocessing: 37

In [34]:
# Apply standard scaling (like Hercules does internally)
scaler = StandardScaler()
scaled_data = scaler.fit_transform(preprocessed_data)

print(f"Data scaled. Shape: {scaled_data.shape}")
print(f"Sample statistics after scaling:")
print(f"  Mean: {scaled_data.mean():.6f}")
print(f"  Std: {scaled_data.std():.6f}")

Data scaled. Shape: (206209, 37)
Sample statistics after scaling:
  Mean: 0.000000
  Std: 1.000000

## 3. Hierarchical K-Means Clustering

In [35]:
# Level 1 clustering: k=147
k_level1 = 147
k_level2 = 3

print(f"Starting Level 1 clustering with k={k_level1}...")
kmeans_l1 = KMeans(n_clusters=k_level1, random_state=42, n_init=10, max_iter=300)
level1_labels = kmeans_l1.fit_predict(scaled_data)
level1_centroids = kmeans_l1.cluster_centers_

print(f"Level 1 clustering complete!")
print(f"  Number of clusters: {k_level1}")
print(f"  Cluster sizes: min={np.bincount(level1_labels).min()}, max={np.bincount(level1_labels).max()}, mean={np.bincount(level1_labels).mean():.1f}")

Starting Level 1 clustering with k=147...
Level 1 clustering complete!
  Number of clusters: 147
  Cluster sizes: min=14, max=3120, mean=1402.8

In [36]:
# Level 2 clustering: k=3 (clustering the level 1 centroids)
print(f"\nStarting Level 2 clustering with k={k_level2}...")
kmeans_l2 = KMeans(n_clusters=k_level2, random_state=42, n_init=10, max_iter=300)
level2_labels = kmeans_l2.fit_predict(level1_centroids)
level2_centroids = kmeans_l2.cluster_centers_

print(f"Level 2 clustering complete!")
print(f"  Number of clusters: {k_level2}")
print(f"  Level 1 clusters per Level 2 cluster: {np.bincount(level2_labels)}")

# Map each data point to its level 2 cluster
level2_labels_full = np.array([level2_labels[l1_label] for l1_label in level1_labels])
print(f"  Data points per Level 2 cluster: {np.bincount(level2_labels_full)}")

Starting Level 2 clustering with k=3...
Level 2 clustering complete!
  Number of clusters: 3
  Level 1 clusters per Level 2 cluster: [  2   2 143]
  Data points per Level 2 cluster: [   148    101 205960]

## 4. Compute Statistics and Rank by Absolute Z-Score

In [37]:
def compute_cluster_statistics(data: np.ndarray, 
                               labels: np.ndarray, 
                               feature_names: List[str],
                               global_means: np.ndarray,
                               level: int) -> pd.DataFrame:
    """
    Compute statistics for each cluster and rank features by absolute deviation.
    Skips identifier columns like user_id, id, etc.
    """
    unique_labels = np.unique(labels)
    all_stats = []
    
    for cluster_id in unique_labels:
        cluster_mask = labels == cluster_id
        cluster_data = data[cluster_mask]
        
        for i, feature_name in enumerate(feature_names):
            # Skip identifier columns (user_id, id, etc.)
            feature_lower = feature_name.lower()
            if any(pattern in feature_lower for pattern in ['user_id', 'userid', '_id', 'id_', 'customer_id', 'customerid']):
                continue
            
            feature_data = cluster_data[:, i]
            feature_data_clean = feature_data[~np.isnan(feature_data)]
            
            if feature_data_clean.size == 0:
                continue
            
            cluster_mean = float(np.mean(feature_data_clean))
            global_mean = float(global_means[i])
            
            # Calculate percentage deviation
            if abs(global_mean) > 1e-10:
                deviation_pct = ((cluster_mean - global_mean) / abs(global_mean)) * 100
            else:
                deviation_pct = cluster_mean * 100
            
            abs_deviation_pct = abs(deviation_pct)
            
            all_stats.append({
                'level': level,
                'cluster_id': int(cluster_id),
                'feature_name': feature_name,
                'cluster_mean': cluster_mean,
                'global_mean': global_mean,
                'deviation_pct': deviation_pct,
                'abs_deviation_pct': abs_deviation_pct,
                'cluster_size': int(cluster_mask.sum())
            })
    
    stats_df = pd.DataFrame(all_stats)
    return stats_df


def get_top_features_per_cluster(stats_df: pd.DataFrame, top_n: int = 10) -> pd.DataFrame:
    """
    Get top N features by absolute deviation for each cluster.
    """
    top_features = stats_df.sort_values('abs_deviation_pct', ascending=False).groupby('cluster_id').head(top_n)
    return top_features


# Compute global means from unscaled data
global_means = np.mean(preprocessed_data, axis=0)

print(f"Computing statistics for Level 1 clusters (excluding ID columns)...")
level1_stats = compute_cluster_statistics(
    preprocessed_data, level1_labels, feature_names, global_means, level=1
)

print(f"Computing statistics for Level 2 clusters (excluding ID columns)...")
level2_stats = compute_cluster_statistics(
    preprocessed_data, level2_labels_full, feature_names, global_means, level=2
)

# Get top 10 features for each cluster
level1_top_features = get_top_features_per_cluster(level1_stats, top_n=10)
level2_top_features = get_top_features_per_cluster(level2_stats, top_n=10)

print(f"\nLevel 1 statistics: {len(level1_stats)} feature-cluster pairs (ID columns excluded)")
print(f"Level 1 top features: {len(level1_top_features)} (top 10 per cluster)")
print(f"\nLevel 2 statistics: {len(level2_stats)} feature-cluster pairs (ID columns excluded)")
print(f"Level 2 top features: {len(level2_top_features)} (top 10 per cluster)")

Computing statistics for Level 1 clusters (excluding ID columns)...
Computing statistics for Level 2 clusters (excluding ID columns)...

Level 1 statistics: 5292 feature-cluster pairs (ID columns excluded)
Level 1 top features: 1470 (top 10 per cluster)

Level 2 statistics: 108 feature-cluster pairs (ID columns excluded)
Level 2 top features: 30 (top 10 per cluster)

In [38]:
# Display sample top features
print("\nSample top features for Level 1, Cluster 0:")
level1_top_features[level1_top_features['cluster_id'] == 0].head()

Sample top features for Level 1, Cluster 0:

,level,cluster_id,feature_name,cluster_mean,global_mean,deviation_pct,abs_deviation_pct,cluster_size
24,1,0,dept_pct_dry_goods_pasta,0.126150,0.025157,401.457523,401.457523,1735
20,1,0,dept_pct_bulk,0.000125,0.000962,-86.980437,86.980437,1735
30,1,0,dept_pct_other,0.000316,0.001361,-76.811309,76.811309,1735
29,1,0,dept_pct_missing,0.000555,0.002348,-76.367773,76.367773,1735
4,1,0,total_products_purchased,39.486455,157.289396,-74.895666,74.895666,1735

## 5. Configure Google Gemini API

In [39]:
# Configure Google Gemini API
GOOGLE_API_KEY = "AIzaSyBVFr1Xck7qLAs0sqHkBMSPCbZLvds394E"

genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-2.5-flash-lite')

print("Google Gemini API configured successfully!")

Google Gemini API configured successfully!

## 6. Generate LLM Descriptions for Clusters

In [40]:
def build_cluster_prompt(cluster_id: int, 
                        top_features_df: pd.DataFrame,
                        level: int,
                        sample_data: np.ndarray,
                        sample_size: int = 5) -> str:
    """
    Build LLM prompt for a single cluster using top features.
    """
    cluster_features = top_features_df[top_features_df['cluster_id'] == cluster_id].sort_values(
        'abs_deviation_pct', ascending=False
    ).head(10)
    
    cluster_size = cluster_features.iloc[0]['cluster_size'] if len(cluster_features) > 0 else 0
    
    prompt = f"""Generate a concise 'title' (max 5-7 words) and 'description' (3-4 sentences) for the Cluster below (Level {level}).

RESPONSE FORMAT: Respond ONLY with a single, valid JSON object.
- Top-level key MUST be the string representation of the 'Cluster ID' provided (e.g., "{cluster_id}").
- Value MUST be a JSON object containing non-empty "title" and "description" string keys.

EXAMPLE:
{{
  "{cluster_id}": {{ "title": "Example Title", "description": "Example description." }}
}}

IMPORTANT: Ensure the entire output is valid JSON. Do NOT include markdown fences (```json ... ```) or any text outside the JSON structure.

--- Cluster Information ---

--- Cluster ID: {cluster_id} (L{level}, {cluster_size} base items) ---

Most Defining Features (Top Deviations from Global Mean):
"""
    
    for idx, row in cluster_features.iterrows():
        direction = "↑" if row['deviation_pct'] > 0 else "↓"
        prompt += f"- {row['feature_name']}: (Cluster: {row['cluster_mean']:.2f} vs Global: {row['global_mean']:.2f}) | {direction} Deviation: {abs(row['deviation_pct']):.2f}%\n"
    
    prompt += f"\n--- End Cluster ID: {cluster_id} ---\n"
    prompt += f"\n--- End Clusters Information ---\n"
    prompt += f"\nGenerate the JSON output for the Cluster ID: {cluster_id}"
    
    return prompt


def parse_llm_response(llm_output: str, cluster_id: int) -> Tuple[Optional[str], Optional[str]]:
    """
    Parse LLM response to extract title and description.
    """
    if not llm_output:
        return None, None
    
    # Try to extract JSON from markdown fences
    json_match = re.search(r'```(?:json)?\s*\n?({.*?})\s*\n?```', llm_output, re.DOTALL)
    if json_match:
        llm_output = json_match.group(1)
    
    # Try to parse JSON
    try:
        parsed = json.loads(llm_output)
        cluster_key = str(cluster_id)
        
        if cluster_key in parsed and isinstance(parsed[cluster_key], dict):
            title = parsed[cluster_key].get('title', '')
            description = parsed[cluster_key].get('description', '')
            return title, description
    except json.JSONDecodeError:
        pass
    
    return None, None


def generate_descriptions_for_level(cluster_ids: List[int],
                                   top_features_df: pd.DataFrame,
                                   level: int,
                                   data: np.ndarray,
                                   max_retries: int = 3) -> pd.DataFrame:
    """
    Generate LLM descriptions for all clusters at a given level.
    Retries on parsing failures up to max_retries times.
    """
    results = []
    
    for i, cluster_id in enumerate(cluster_ids):
        print(f"Processing Level {level}, Cluster {cluster_id} ({i+1}/{len(cluster_ids)})...")
        
        # Build prompt
        prompt = build_cluster_prompt(cluster_id, top_features_df, level, data)
        
        # Retry logic
        title, description = None, None
        for attempt in range(max_retries):
            try:
                response = model.generate_content(prompt)
                llm_output = response.text
                
                # Parse response
                title, description = parse_llm_response(llm_output, cluster_id)
                
                if title and description:
                    results.append({
                        'level': level,
                        'cluster_id': cluster_id,
                        'title': title,
                        'description': description
                    })
                    print(f"  ✓ Success: {title[:50]}...")
                    break  # Success, exit retry loop
                else:
                    if attempt < max_retries - 1:
                        print(f"  ⟳ Retry {attempt + 1}/{max_retries - 1}: Failed to parse, retrying...")
                    else:
                        print(f"  ✗ Failed to parse response after {max_retries} attempts")
                        results.append({
                            'level': level,
                            'cluster_id': cluster_id,
                            'title': f"Cluster {cluster_id} (Level {level})",
                            'description': "Description generation failed after retries."
                        })
            except Exception as e:
                if attempt < max_retries - 1:
                    print(f"  ⟳ Retry {attempt + 1}/{max_retries - 1}: Error ({e}), retrying...")
                else:
                    print(f"  ✗ Error after {max_retries} attempts: {e}")
                    results.append({
                        'level': level,
                        'cluster_id': cluster_id,
                        'title': f"Cluster {cluster_id} (Level {level})",
                        'description': f"Error: {str(e)}"
                    })
    
    return pd.DataFrame(results)


print("Generating descriptions for Level 1 clusters...")
level1_descriptions = generate_descriptions_for_level(
    cluster_ids=list(range(k_level1)),
    top_features_df=level1_top_features,
    level=1,
    data=preprocessed_data
)

print(f"\n{'='*80}")
print(f"Level 1 complete: {len(level1_descriptions)} clusters processed")
print(f"{'='*80}\n")

Generating descriptions for Level 1 clusters...
Processing Level 1, Cluster 0 (1/147)...
  ✓ Success: Pasta Lovers, Fewer Orders...
Processing Level 1, Cluster 1 (2/147)...
  ✓ Success: Weekend Produce Shoppers, No Alcohol...
Processing Level 1, Cluster 2 (3/147)...
  ✓ Success: High Baby Products, Diverse Basket...
Processing Level 1, Cluster 3 (4/147)...
  ✓ Success: Weekend Bulk Buy & Bakery Shoppers...
Processing Level 1, Cluster 4 (5/147)...
  ✓ Success: High Volume, Diverse Product Shoppers...
Processing Level 1, Cluster 5 (6/147)...
  ✓ Success: High Personal Care, Low Overall Purchases...
Processing Level 1, Cluster 6 (7/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: Evening Shoppers, High Basket Diversity...
Processing Level 1, Cluster 7 (8/147)...
  ✓ Success: Pet and Household Product Dominance...
Processing Level 1, Cluster 8 (9/147)...
  ✓ Success: Weekend Shoppers, Dairy & Eggs Focus...
Processing Level 1, Cluster 9 (10/147)...
  ✓ Success: High Beverage, Low Variety Shoppers...
Processing Level 1, Cluster 10 (11/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: High-Volume, Frequent, Diverse Shoppers...
Processing Level 1, Cluster 11 (12/147)...
  ✓ Success: Frequent, Diverse, and In-Store Shoppers...
Processing Level 1, Cluster 12 (13/147)...
  ✓ Success: Meat and Seafood Dominant Stores...
Processing Level 1, Cluster 13 (14/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: International Focus, Lower Purchase Volume...
Processing Level 1, Cluster 14 (15/147)...
  ✓ Success: Evening Shoppers, Few Product Types...
Processing Level 1, Cluster 15 (16/147)...
  ✓ Success: Weekend Shoppers, Pantry & Canned Goods Lovers...
Processing Level 1, Cluster 16 (17/147)...
  ✓ Success: Snack and Beverage Focused Stores...
Processing Level 1, Cluster 17 (18/147)...
  ✓ Success: Household Shoppers, Fewer Orders...
Processing Level 1, Cluster 18 (19/147)...
  ✓ Success: High Alcohol, Low General Product Buyers...
Processing Level 1, Cluster 19 (20/147)...
  ✓ Success: High Produce and Reorder Rate...
Processing Level 1, Cluster 20 (21/147)...
  ✓ Success: Bulk and Snacks Focused Shoppers...
Processing Level 1, Cluster 21 (22/147)...
  ✓ Success: Canned Goods Lovers, Fewer Items...
Processing Level 1, Cluster 22 (23/147)...
  ✓ Success: Household Goods Shoppers, Low Volume...
Processing Level 1, Cluster 23 (24/147)...
  ✓ Success: Diversified Shoppers: High Other, Alcohol, Househo...
Processing Level 1, Cluster 24 (25/147)...
  ✓ Success: Weekend Shoppers, Fewer Aisles...
Processing Level 1, Cluster 25 (26/147)...
  ✓ Success: High Alcohol, Low Produce Focus...
Processing Level 1, Cluster 26 (27/147)...
  ✓ Success: Dominant Baby and Household Goods...
Processing Level 1, Cluster 27 (28/147)...
  ✓ Success: High Volume, Diverse Product Shoppers...
Processing Level 1, Cluster 28 (29/147)...
  ✓ Success: High Missing, Frozen, Personal Care Items...
Processing Level 1, Cluster 29 (30/147)...
  ✓ Success: Breakfast and Snacks Focus...
Processing Level 1, Cluster 30 (31/147)...
  ✓ Success: High Meat & Seafood, Low Other Products...
Processing Level 1, Cluster 31 (32/147)...
  ✓ Success: High Dairy, Low Alcohol, Fewer Weekends...
Processing Level 1, Cluster 32 (33/147)...
  ✓ Success: Frequent, Diverse Product Buyers...
Processing Level 1, Cluster 33 (34/147)...
  ✓ Success: High Deli Sales, Low Product Variety...
Processing Level 1, Cluster 34 (35/147)...
  ✓ Success: Low Order Volume, Diverse Purchase...
Processing Level 1, Cluster 35 (36/147)...
  ✓ Success: Low Bulk, High Reorder Rate...
Processing Level 1, Cluster 36 (37/147)...
  ✓ Success: Dairy & Eggs Focused Shoppers...
Processing Level 1, Cluster 37 (38/147)...
  ✓ Success: Alcohol-Dominant Shops...
Processing Level 1, Cluster 38 (39/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ⟳ Retry 2/2: Failed to parse, retrying...
  ✓ Success: Beverage-Centric, Low-Volume Buyers...
Processing Level 1, Cluster 39 (40/147)...
  ✓ Success: Snack Enthusiasts, Less Household Staples...
Processing Level 1, Cluster 40 (41/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: Low Purchase, High Missing Data...
Processing Level 1, Cluster 41 (42/147)...
  ✓ Success: High Basket Size, Diverse Product Range...
Processing Level 1, Cluster 42 (43/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ⟳ Retry 2/2: Failed to parse, retrying...
  ✓ Success: Produce Focused Shoppers...
Processing Level 1, Cluster 43 (44/147)...
  ✓ Success: High Breakfast, Low Specialty Sales...
Processing Level 1, Cluster 44 (45/147)...
  ✓ Success: Less Frequent Shopping, More Bakery/Frozen...
Processing Level 1, Cluster 45 (46/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: Infrequent, Low-Volume Shoppers...
Processing Level 1, Cluster 46 (47/147)...
  ✓ Success: High Missing Data, Low Product Variety...
Processing Level 1, Cluster 47 (48/147)...
  ✓ Success: Dominant Bakery, Few Unique Products...
Processing Level 1, Cluster 48 (49/147)...
  ✓ Success: Personal Care & Household Product Focus...
Processing Level 1, Cluster 49 (50/147)...
  ✓ Success: International Goods and Deli Focus...
Processing Level 1, Cluster 50 (51/147)...
  ✓ Success: Breakfast Enthusiasts, Low Order Volume...
Processing Level 1, Cluster 51 (52/147)...
  ✓ Success: Frequent Shoppers, Snack & Beverage Enthusiasts...
Processing Level 1, Cluster 52 (53/147)...
  ✓ Success: Produce Dominant, Minimal Other Departments...
Processing Level 1, Cluster 53 (54/147)...
  ✓ Success: Specialty Grocer, Limited Basket Size...
Processing Level 1, Cluster 54 (55/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: High Pantry, Low Overall Purchases...
Processing Level 1, Cluster 55 (56/147)...
  ✓ Success: Produce-Heavy Shoppers with Fewer Items...
Processing Level 1, Cluster 56 (57/147)...
  ✓ Success: Infrequent Canned Goods & Pantry Shoppers...
Processing Level 1, Cluster 57 (58/147)...
  ✓ Success: Produce Lovers, Few Alcohol/Baby Items...
Processing Level 1, Cluster 58 (59/147)...
  ✓ Success: Frequent, High Basket Size Shoppers...
Processing Level 1, Cluster 59 (60/147)...
  ✓ Success: Consistent Late-Night Shoppers, Few Product Catego...
Processing Level 1, Cluster 60 (61/147)...
  ✓ Success: High Pasta, Low Overall Purchases...
Processing Level 1, Cluster 61 (62/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: Infrequent Buyers, Low Order Value...
Processing Level 1, Cluster 62 (63/147)...
  ✓ Success: Infrequent, Consistent Bulk Buyers...
Processing Level 1, Cluster 63 (64/147)...
  ✓ Success: Frequent, Diverse, and Loyal Shoppers...
Processing Level 1, Cluster 64 (65/147)...
  ✓ Success: Pet & Household Focused Grocer...
Processing Level 1, Cluster 65 (66/147)...
  ✓ Success: Dominant Snack Department Cluster...
Processing Level 1, Cluster 66 (67/147)...
  ✓ Success: High Frozen, Moderate Reorder Rate...
Processing Level 1, Cluster 67 (68/147)...
  ✓ Success: Frequent Alcohol and Household Shoppers...
Processing Level 1, Cluster 68 (69/147)...
  ✓ Success: Baby Products Dominated Retailers...
Processing Level 1, Cluster 69 (70/147)...
  ✓ Success: Dairy & Eggs Dominance, Less Alcohol...
Processing Level 1, Cluster 70 (71/147)...
  ✓ Success: Produce and Unique Products Focus...
Processing Level 1, Cluster 71 (72/147)...
  ✓ Success: Low Purchased & Missing Item Department...
Processing Level 1, Cluster 72 (73/147)...
  ✓ Success: High Deli, Low Variety Shoppers...
Processing Level 1, Cluster 73 (74/147)...
  ✓ Success: Dominant Beverage Department Cluster...
Processing Level 1, Cluster 74 (75/147)...
  ✓ Success: Pasta Lovers, Weekend Shoppers...
Processing Level 1, Cluster 75 (76/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: High International, Low Product Variety...
Processing Level 1, Cluster 76 (77/147)...
  ✓ Success: Produce Focused, Low Purchase Volume...
Processing Level 1, Cluster 77 (78/147)...
  ✓ Success: Overwhelmingly Snack-Centric Departments...
Processing Level 1, Cluster 78 (79/147)...
  ✓ Success: Weekend Produce Shoppers...
Processing Level 1, Cluster 79 (80/147)...
  ✓ Success: Dominance of Frozen, Few Other Departments...
Processing Level 1, Cluster 80 (81/147)...
  ✓ Success: Frequent, Diverse, and Large Orders...
Processing Level 1, Cluster 81 (82/147)...
  ✓ Success: High Meat/Seafood, Low Overall Variety...
Processing Level 1, Cluster 82 (83/147)...
  ✓ Success: High Beverage Sales, Low Overall Purchases...
Processing Level 1, Cluster 83 (84/147)...
  ✓ Success: High Dairy & Egg Dominance...
Processing Level 1, Cluster 84 (85/147)...
  ✓ Success: Infrequent Pasta Lovers, Few Items...
Processing Level 1, Cluster 85 (86/147)...
  ✓ Success: Produce Focus, Infrequent Large Orders...
Processing Level 1, Cluster 86 (87/147)...
  ✓ Success: High-Volume Baby Product Shoppers...
Processing Level 1, Cluster 87 (88/147)...
  ✓ Success: High Deli, Low Other Products...
Processing Level 1, Cluster 88 (89/147)...
  ✓ Success: High Personal Care, Household Goods Focus...
Processing Level 1, Cluster 89 (90/147)...
  ✓ Success: Canned Goods Focused, Low Variety Shoppers...
Processing Level 1, Cluster 90 (91/147)...
  ✓ Success: Breakfast Focus, Limited Variety...
Processing Level 1, Cluster 91 (92/147)...
  ✓ Success: Frequent, Diverse, Big Basket Shoppers...
Processing Level 1, Cluster 92 (93/147)...
  ✓ Success: International Canned Goods Buyers...
Processing Level 1, Cluster 93 (94/147)...
  ✓ Success: Bulk and Snacks Dominant Grocery Cluster...
Processing Level 1, Cluster 94 (95/147)...
  ✓ Success: High Volume, Diverse, Loyal Shoppers...
Processing Level 1, Cluster 95 (96/147)...
  ✓ Success: Household & Personal Care Focus...
Processing Level 1, Cluster 96 (97/147)...
  ✓ Success: Dominance of Frozen Foods, Low Product Variety...
Processing Level 1, Cluster 97 (98/147)...
  ✓ Success: High Beverage Sales, Lower Other Categories...
Processing Level 1, Cluster 98 (99/147)...
  ✓ Success: High Purchase Volume, Unique Aisle Shoppers...
Processing Level 1, Cluster 99 (100/147)...
  ✓ Success: Pet Supplies Dominate, Household Goods Secondary...
Processing Level 1, Cluster 100 (101/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: Specialty & Exploration Shoppers...
Processing Level 1, Cluster 101 (102/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ⟳ Retry 2/2: Failed to parse, retrying...
  ✓ Success: Frequent shoppers, fresh produce focus...
Processing Level 1, Cluster 102 (103/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: Weekend Shoppers with Diverse Product Choices...
Processing Level 1, Cluster 103 (104/147)...
  ✓ Success: Canned Goods Enthusiasts...
Processing Level 1, Cluster 104 (105/147)...
  ✓ Success: High Canned Goods, Low Specialty Items...
Processing Level 1, Cluster 105 (106/147)...
  ✓ Success: Low Purchase Volume, Infrequent Buyers...
Processing Level 1, Cluster 106 (107/147)...
  ✓ Success: High Household & Beverage Spending...
Processing Level 1, Cluster 107 (108/147)...
  ✓ Success: High Produce, Low Alcohol & Order Volume...
Processing Level 1, Cluster 108 (109/147)...
  ✓ Success: High Deli Sales, Low Other Depts...
Processing Level 1, Cluster 109 (110/147)...
  ✓ Success: Dominant Baby Products, Fewer Other Categories...
Processing Level 1, Cluster 110 (111/147)...
  ✓ Success: Pantry Focused Shoppers, Fewer Unique Items...
Processing Level 1, Cluster 111 (112/147)...
  ✓ Success: Dominant Frozen Goods Shoppers...
Processing Level 1, Cluster 112 (113/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: Pantry Shoppers, Low Reorder Rate...
Processing Level 1, Cluster 113 (114/147)...
  ✓ Success: Dominant Dairy and Egg Focus...
Processing Level 1, Cluster 114 (115/147)...
  ✓ Success: High Volume, Diverse Product Shoppers...
Processing Level 1, Cluster 115 (116/147)...
  ✓ Success: Dominant Bakery, Few Unique Products...
Processing Level 1, Cluster 116 (117/147)...
  ✓ Success: Bakery Focused, Low Volume Shoppers...
Processing Level 1, Cluster 117 (118/147)...
  ✓ Success: Pets and Household Essentials Focus...
Processing Level 1, Cluster 118 (119/147)...
  ✓ Success: Weekend shoppers, focus on canned goods...
Processing Level 1, Cluster 119 (120/147)...
  ✓ Success: Larger Baskets, Less Frequent, No Alcohol...
Processing Level 1, Cluster 120 (121/147)...
  ✓ Success: Unusual Purchases: High 'Other', Low Variety...
Processing Level 1, Cluster 121 (122/147)...
  ✓ Success: Bulk and Snack Focused, Fewer Unique Products...
Processing Level 1, Cluster 122 (123/147)...
  ✓ Success: Produce Dominant, Minimal Other Departments...
Processing Level 1, Cluster 123 (124/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: High Bakery Sales, High Reorder Rate...
Processing Level 1, Cluster 124 (125/147)...
  ✓ Success: Frozen Focus, Lower Purchase Volume...
Processing Level 1, Cluster 125 (126/147)...
  ✓ Success: Frequent Buyers of Diverse Products...
Processing Level 1, Cluster 126 (127/147)...
  ✓ Success: Weekend Shoppers, Pantry & Frozen Focus...
Processing Level 1, Cluster 127 (128/147)...
  ✓ Success: High Dairy & Egg, High Order Volume...
Processing Level 1, Cluster 128 (129/147)...
  ✓ Success: Personal Care & Household Focus...
Processing Level 1, Cluster 129 (130/147)...
  ✓ Success: International Baby & Specialty Shoppers...
Processing Level 1, Cluster 130 (131/147)...
  ✓ Success: Less Frequent Orders, More Pantry Items...
Processing Level 1, Cluster 131 (132/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: High Meat & Seafood, Low Overall Purchase...
Processing Level 1, Cluster 132 (133/147)...
  ✓ Success: Frequent, Diverse, and Loyal Shoppers...
Processing Level 1, Cluster 133 (134/147)...
  ✓ Success: Breakfast Dominant, Few Other Categories...
Processing Level 1, Cluster 134 (135/147)...
  ✓ Success: Beverage & Snacks Dominant, Other Categories Absen...
Processing Level 1, Cluster 135 (136/147)...
  ✓ Success: Early Morning Non-Alcohol Shoppers...
Processing Level 1, Cluster 136 (137/147)...
  ✓ Success: Snack Focused, Infrequent Shoppers...
Processing Level 1, Cluster 137 (138/147)...
  ✓ Success: Dominant Household Goods Retailers...
Processing Level 1, Cluster 138 (139/147)...
  ✓ Success: Produce-Dominant Stores with Many Items...
Processing Level 1, Cluster 139 (140/147)...
  ✓ Success: Large Baskets, Infrequent Buyers...
Processing Level 1, Cluster 140 (141/147)...
  ✓ Success: High Product Variety, Large Baskets...
Processing Level 1, Cluster 141 (142/147)...
  ✓ Success: High Personal Care, Household Goods Focus...
Processing Level 1, Cluster 142 (143/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: High Pasta, Low Alcohol & Babies...
Processing Level 1, Cluster 143 (144/147)...
  ⟳ Retry 1/2: Failed to parse, retrying...
  ✓ Success: Low Bulk, Baby, Pet, Alcohol Purchase Cluster...
Processing Level 1, Cluster 144 (145/147)...
  ✓ Success: Frequent Dairy/Egg Buyers, Infrequent Orders...
Processing Level 1, Cluster 145 (146/147)...
  ✓ Success: High Bulk, Low Alcohol, Frequent Buyers...
Processing Level 1, Cluster 146 (147/147)...
  ✓ Success: Produce Focus, Lower Order Frequency...

================================================================================
Level 1 complete: 147 clusters processed
================================================================================

In [41]:
print("Generating descriptions for Level 2 clusters...")
level2_descriptions = generate_descriptions_for_level(
    cluster_ids=list(range(k_level2)),
    top_features_df=level2_top_features,
    level=2,
    data=preprocessed_data
)

print(f"\n{'='*80}")
print(f"Level 2 complete: {len(level2_descriptions)} clusters processed")
print(f"{'='*80}\n")

Generating descriptions for Level 2 clusters...
Processing Level 2, Cluster 0 (1/3)...
  ✓ Success: High Bulk and Snacks, Few Unique Items...
Processing Level 2, Cluster 1 (2/3)...
  ✓ Success: Frequent Beverage & Other Buyers...
Processing Level 2, Cluster 2 (3/3)...
  ✓ Success: Average Spending, High Unique Products...

================================================================================
Level 2 complete: 3 clusters processed
================================================================================

## 7. Export Results to CSV

In [42]:
# Combine level 1 and level 2 descriptions
all_descriptions = pd.concat([level1_descriptions, level2_descriptions], ignore_index=True)
all_descriptions = all_descriptions.sort_values(['level', 'cluster_id'])

print(f"Total clusters with descriptions: {len(all_descriptions)}")
print(f"\nSample descriptions:")
all_descriptions.head(10)

Total clusters with descriptions: 150

Sample descriptions:

,level,cluster_id,title,description
0,1,0,"Pasta Lovers, Fewer Orders",This cluster significantly over-indexes on pas...
1,1,1,"Weekend Produce Shoppers, No Alcohol",This cluster represents shoppers who predomina...
2,1,2,"High Baby Products, Diverse Basket","This cluster heavily features baby products, s..."
3,1,3,Weekend Bulk Buy & Bakery Shoppers,This cluster represents customers who primaril...
4,1,4,"High Volume, Diverse Product Shoppers",This cluster represents shoppers who purchase ...
5,1,5,"High Personal Care, Low Overall Purchases",This cluster shows a strong preference for per...
6,1,6,"Evening Shoppers, High Basket Diversity",This cluster represents customers who primaril...
7,1,7,Pet and Household Product Dominance,This cluster is heavily characterized by a sig...
8,1,8,"Weekend Shoppers, Dairy & Eggs Focus",This cluster represents shoppers who predomina...
9,1,9,"High Beverage, Low Variety Shoppers",This cluster exhibits a significantly higher p...

In [43]:
# Save cluster details CSV
output_dir = r'C:\Users\weezh\OneDrive\Desktop\pyhercules\evaluation\LLM Silhouette Score'
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

cluster_details_path = os.path.join(output_dir, f'instacart_cluster_details_{timestamp}.csv')
all_descriptions.to_csv(cluster_details_path, index=False)
print(f"\n✓ Cluster details saved to: {cluster_details_path}")

✓ Cluster details saved to: C:\Users\weezh\OneDrive\Desktop\pyhercules\evaluation\LLM Silhouette Score\instacart_cluster_details_20260310_095926.csv

In [44]:
# Save top features (defining characteristics) CSV
all_top_features = pd.concat([level1_top_features, level2_top_features], ignore_index=True)
all_top_features = all_top_features.sort_values(['level', 'cluster_id', 'abs_deviation_pct'], ascending=[True, True, False])

top_features_path = os.path.join(output_dir, f'instacart_top_features_{timestamp}.csv')
all_top_features.to_csv(top_features_path, index=False)
print(f"✓ Top defining features saved to: {top_features_path}")

✓ Top defining features saved to: C:\Users\weezh\OneDrive\Desktop\pyhercules\evaluation\LLM Silhouette Score\instacart_top_features_20260310_095926.csv

In [45]:
# Display summary statistics
print(f"\n{'='*80}")
print(f"SUMMARY")
print(f"{'='*80}")
print(f"Dataset: {df.shape[0]} rows, {df.shape[1]} original columns")
print(f"Preprocessed features: {len(feature_names)}")
print(f"\nClustering:")
print(f"  Level 1: {k_level1} clusters")
print(f"  Level 2: {k_level2} clusters")
print(f"\nLLM Descriptions:")
print(f"  Total clusters described: {len(all_descriptions)}")
print(f"  Successful: {len(all_descriptions[all_descriptions['description'] != 'Description generation failed.'])}")
print(f"\nOutput files:")
print(f"  1. {cluster_details_path}")
print(f"  2. {top_features_path}")
print(f"{'='*80}")

================================================================================
SUMMARY
================================================================================
Dataset: 206209 rows, 37 original columns
Preprocessed features: 37

Clustering:
  Level 1: 147 clusters
  Level 2: 3 clusters

LLM Descriptions:
  Total clusters described: 150
  Successful: 150

Output files:
  1. C:\Users\weezh\OneDrive\Desktop\pyhercules\evaluation\LLM Silhouette Score\instacart_cluster_details_20260310_095926.csv
  2. C:\Users\weezh\OneDrive\Desktop\pyhercules\evaluation\LLM Silhouette Score\instacart_top_features_20260310_095926.csv
================================================================================